// Keep task progress visible in the workbench after replacing the legacy panel.
export const manipulationPhases: Record<string, string> = {
  idle: "待命",
  planning: "观察目标",
  grasp_candidates: "生成抓取候选",
  selected_grasp: "选择抓取姿态",
  pregrasp: "接近目标",
  approach: "下降抓取",
  close_gripper: "夹紧物体",
  lift: "抬升物体",
  lift_verified: "抬升已验证",
  placement_inference: "生成放置候选",
  placement_candidates: "筛选放置姿态",
  selected_placement: "准备放置",
  transport: "搬运物体",
  place_approach: "下降放置",
  release: "释放物体",
  retreat: "退离目标",
  observation: "获取目标点云",
  settle_grasp: "稳定夹持",
  finish: "验证放置结果",
  attempt_started: "开始执行",
  attempt_finished: "检查执行结果",
  model_fallback: "升级模型处理",
  fallback_keep_grasp: "保留抓取，升级放置",
  fallback_reobserve: "重新观察目标",
  fallback_retreat: "退离后重新抓取",
  holding_resumed: "继续放置手中物体",
  held_geometry_reused: "沿用持物几何",
  free_space_selected: "已选定空闲放置位置",
};

export const manipulationStates: Record<string, string> = {
  accepted: "已接收",
  running: "执行中",
  completed: "已完成",
  failed: "未完成",
  cancelled: "已中断",
};
